/*
 * Generated from src/ by scripts/build-browser-bundles.js.
 * Do not edit this file directly; update src/ and run npm run build.
 */
var StreamJamsOverlay = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __typeError = (msg) => {
    throw TypeError(msg);
  };
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
  var __accessCheck = (obj, member, msg) => member.has(obj) || __typeError("Cannot " + msg);
  var __privateGet = (obj, member, getter) => (__accessCheck(obj, member, "read from private field"), getter ? getter.call(obj) : member.get(obj));
  var __privateAdd = (obj, member, value) => member.has(obj) ? __typeError("Cannot add the same private member more than once") : member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
  var __privateSet = (obj, member, value, setter) => (__accessCheck(obj, member, "write to private field"), setter ? setter.call(obj, value) : member.set(obj, value), value);
  var __privateMethod = (obj, member, method) => (__accessCheck(obj, member, "access private method"), method);

  // src/app/overlayApp.js
  var overlayApp_exports = {};
  __export(overlayApp_exports, {
    startOverlayApp: () => startOverlayApp
  });

  // src/config/overlayConfig.js
  var INTEGRATIONS = /* @__PURE__ */ new Set(["pear-youtube-music", "mock"]);
  var TRANSPORTS = /* @__PURE__ */ new Set(["auto", "ws", "poll"]);
  var VIEWS = /* @__PURE__ */ new Set(["full", "compact"]);
  var IDLE_MODES = /* @__PURE__ */ new Set(["none", "hide", "compact"]);
  var THEMES = /* @__PURE__ */ new Set(["dark", "light"]);
  function parseOverlayConfig(input = ((_b) => (_b = ((_a) => (_a = globalThis.location) == null ? void 0 : _a.href)()) != null ? _b : "")()) {
    var _a2, _b2;
    const url = new URL(input, "http://localhost/index.html");
    const params = url.searchParams;
    const integration = (_a2 = params.get("integration")) != null ? _a2 : "";
    const errors = [];
    if (!integration) {
      errors.push("Missing integration. Open setup.html to generate an overlay URL.");
    } else if (!INTEGRATIONS.has(integration)) {
      errors.push(`Unsupported integration: ${integration}`);
    }
    const transport = readEnum(params, "transport", TRANSPORTS, "auto", errors);
    const initialView = readEnum(params, "initialView", VIEWS, "full", errors);
    const idleMode = readEnum(params, "idleMode", IDLE_MODES, "none", errors);
    const theme = readEnum(params, "theme", THEMES, "dark", errors);
    const idleAfter = readInteger(params, "idleAfter", 30, { min: 1, max: 600 }, errors);
    const customCss = normalizeCustomCss((_b2 = params.get("customCss")) != null ? _b2 : "", errors);
    let host = "";
    let port = 0;
    if (integration === "pear-youtube-music") {
      host = (params.get("host") || "127.0.0.1").trim();
      port = readInteger(params, "port", 26538, { min: 1, max: 65535 }, errors);
      if (!host) {
        errors.push("Host is required for Pear YouTube Music.");
      }
    }
    if (errors.length > 0) {
      return { ok: false, errors };
    }
    return {
      ok: true,
      integration,
      host,
      port,
      transport,
      initialView,
      idleMode,
      idleAfter,
      theme,
      customCss
    };
  }
  function readEnum(params, key, allowed, fallback, errors) {
    const value = params.get(key) || fallback;
    if (!allowed.has(value)) {
      errors.push(`${key} must be one of: ${Array.from(allowed).join(", ")}`);
      return fallback;
    }
    return value;
  }
  function readInteger(params, key, fallback, bounds, errors) {
    const raw = params.get(key);
    if (raw === null || raw === "") {
      return fallback;
    }
    const value = Number(raw);
    if (!Number.isInteger(value) || value < bounds.min || value > bounds.max) {
      errors.push(`${key} must be an integer from ${bounds.min} to ${bounds.max}`);
      return fallback;
    }
    return value;
  }
  function normalizeCustomCss(value, errors) {
    const trimmed = value.trim();
    if (!trimmed) {
      return "";
    }
    if (/^(https?:)?\/\//i.test(trimmed) || trimmed.startsWith("/") || trimmed.includes("..")) {
      errors.push("customCss must be a same-folder or same-origin relative path.");
      return "";
    }
    return trimmed;
  }

  // src/sources/musicSource.js
  var _listeners;
  var EventEmitter = class {
    constructor() {
      __privateAdd(this, _listeners, /* @__PURE__ */ new Map());
    }
    on(type, handler) {
      var _a;
      const handlers = (_a = __privateGet(this, _listeners).get(type)) != null ? _a : /* @__PURE__ */ new Set();
      handlers.add(handler);
      __privateGet(this, _listeners).set(type, handlers);
      return () => handlers.delete(handler);
    }
    emit(type, payload) {
      var _a;
      for (const handler of (_a = __privateGet(this, _listeners).get(type)) != null ? _a : []) {
        handler(payload);
      }
    }
  };
  _listeners = new WeakMap();

  // src/state/playerState.js
  function normalizePearSong(payload, now = Date.now()) {
    return normalizePlayerState({
      trackId: payload.videoId || payload.url || payload.title,
      title: payload.title,
      artist: payload.artist,
      album: payload.album,
      artworkUrl: payload.imageSrc,
      durationSeconds: payload.songDuration,
      elapsedSeconds: payload.elapsedSeconds,
      isPlaying: payload.isPaused === false,
      sourceName: "YouTube Music",
      updatedAt: now
    });
  }
  function normalizePlayerState(input = {}) {
    const durationSeconds = positiveNumber(input.durationSeconds);
    const elapsedSeconds = clamp(positiveNumber(input.elapsedSeconds), 0, durationSeconds || 0);
    return {
      trackId: stringOrFallback(input.trackId, ""),
      title: stringOrFallback(input.title, "No track"),
      artist: stringOrFallback(input.artist, "Unknown artist"),
      album: stringOrFallback(input.album, ""),
      artworkUrl: stringOrFallback(input.artworkUrl, ""),
      durationSeconds,
      elapsedSeconds,
      isPlaying: Boolean(input.isPlaying),
      sourceName: stringOrFallback(input.sourceName, ""),
      updatedAt: Number.isFinite(input.updatedAt) ? input.updatedAt : Date.now()
    };
  }
  function stringOrFallback(value, fallback) {
    return typeof value === "string" && value.trim() ? value.trim() : fallback;
  }
  function positiveNumber(value) {
    const number = Number(value);
    return Number.isFinite(number) && number > 0 ? number : 0;
  }
  function clamp(value, min, max) {
    if (max <= min) {
      return min;
    }
    return Math.min(max, Math.max(min, value));
  }

  // src/sources/mockMusicSource.js
  var DEMO_TRACKS = [
    {
      trackId: "demo-1",
      title: "Midnight Channel",
      artist: "Stream Jams",
      album: "Overlay Tests",
      durationSeconds: 184,
      artworkUrl: ""
    },
    {
      trackId: "demo-2",
      title: "Low Latency Lights",
      artist: "Aster Pulse",
      album: "Scene Switch",
      durationSeconds: 216,
      artworkUrl: ""
    }
  ];
  var _timer, _startedAt, _trackIndex, _state, _MockMusicSource_instances, publish_fn;
  var MockMusicSource = class extends EventEmitter {
    constructor() {
      super(...arguments);
      __privateAdd(this, _MockMusicSource_instances);
      __privateAdd(this, _timer, 0);
      __privateAdd(this, _startedAt, 0);
      __privateAdd(this, _trackIndex, 0);
      __privateAdd(this, _state, null);
    }
    connect() {
      this.emit("connection", { state: "connected", message: "Mock source connected" });
      __privateSet(this, _startedAt, Date.now());
      __privateMethod(this, _MockMusicSource_instances, publish_fn).call(this);
      __privateSet(this, _timer, globalThis.setInterval(() => __privateMethod(this, _MockMusicSource_instances, publish_fn).call(this), 1e3));
    }
    disconnect() {
      globalThis.clearInterval(__privateGet(this, _timer));
      this.emit("connection", { state: "disconnected", message: "Mock source disconnected" });
    }
    getCurrentState() {
      return __privateGet(this, _state);
    }
  };
  _timer = new WeakMap();
  _startedAt = new WeakMap();
  _trackIndex = new WeakMap();
  _state = new WeakMap();
  _MockMusicSource_instances = new WeakSet();
  publish_fn = function() {
    const track = DEMO_TRACKS[__privateGet(this, _trackIndex)];
    const elapsedSeconds = Math.floor((Date.now() - __privateGet(this, _startedAt)) / 1e3);
    if (elapsedSeconds >= track.durationSeconds) {
      __privateSet(this, _trackIndex, (__privateGet(this, _trackIndex) + 1) % DEMO_TRACKS.length);
      __privateSet(this, _startedAt, Date.now());
    }
    __privateSet(this, _state, normalizePlayerState({
      ...DEMO_TRACKS[__privateGet(this, _trackIndex)],
      elapsedSeconds: Math.floor((Date.now() - __privateGet(this, _startedAt)) / 1e3),
      isPlaying: true,
      sourceName: "Mock",
      updatedAt: Date.now()
    }));
    this.emit("state", __privateGet(this, _state));
  };

  // src/sources/pearYoutubeMusicSource.js
  var _config, _fetch, _WebSocket, _socket, _pollTimer, _reconnectTimer, _webSocketRetryTimer, _state2, _stopped, _PearYoutubeMusicSource_instances, connectWebSocket_fn, fallbackFromWebSocket_fn, startPolling_fn, pollOnce_fn, requestSong_fn, handleSocketMessage_fn, publishPearPayload_fn, publishPartialState_fn, mergeSameTrackMissingFields_fn, scheduleWebSocketRetry_fn;
  var PearYoutubeMusicSource = class extends EventEmitter {
    constructor(config, dependencies = {}) {
      var _a, _b, _c;
      super();
      __privateAdd(this, _PearYoutubeMusicSource_instances);
      __privateAdd(this, _config);
      __privateAdd(this, _fetch);
      __privateAdd(this, _WebSocket);
      __privateAdd(this, _socket, null);
      __privateAdd(this, _pollTimer, 0);
      __privateAdd(this, _reconnectTimer, 0);
      __privateAdd(this, _webSocketRetryTimer, 0);
      __privateAdd(this, _state2, null);
      __privateAdd(this, _stopped, false);
      __privateSet(this, _config, config);
      __privateSet(this, _fetch, (_b = dependencies.fetch) != null ? _b : (_a = globalThis.fetch) == null ? void 0 : _a.bind(globalThis));
      __privateSet(this, _WebSocket, (_c = dependencies.WebSocket) != null ? _c : globalThis.WebSocket);
    }
    connect() {
      __privateSet(this, _stopped, false);
      this.emit("connection", { state: "connecting", message: "Connecting to Pear Desktop" });
      if (__privateGet(this, _config).transport === "poll") {
        __privateMethod(this, _PearYoutubeMusicSource_instances, startPolling_fn).call(this);
        return;
      }
      __privateMethod(this, _PearYoutubeMusicSource_instances, connectWebSocket_fn).call(this);
    }
    disconnect() {
      var _a, _b;
      __privateSet(this, _stopped, true);
      globalThis.clearInterval(__privateGet(this, _pollTimer));
      globalThis.clearTimeout(__privateGet(this, _reconnectTimer));
      globalThis.clearTimeout(__privateGet(this, _webSocketRetryTimer));
      (_b = (_a = __privateGet(this, _socket)) == null ? void 0 : _a.close) == null ? void 0 : _b.call(_a);
      this.emit("connection", { state: "disconnected", message: "Disconnected" });
    }
    getCurrentState() {
      return __privateGet(this, _state2);
    }
    async testConnection() {
      const response = await __privateMethod(this, _PearYoutubeMusicSource_instances, requestSong_fn).call(this);
      return response.ok || response.status === 204;
    }
  };
  _config = new WeakMap();
  _fetch = new WeakMap();
  _WebSocket = new WeakMap();
  _socket = new WeakMap();
  _pollTimer = new WeakMap();
  _reconnectTimer = new WeakMap();
  _webSocketRetryTimer = new WeakMap();
  _state2 = new WeakMap();
  _stopped = new WeakMap();
  _PearYoutubeMusicSource_instances = new WeakSet();
  connectWebSocket_fn = function() {
    if (!__privateGet(this, _WebSocket)) {
      __privateMethod(this, _PearYoutubeMusicSource_instances, fallbackFromWebSocket_fn).call(this);
      return;
    }
    const socket = new (__privateGet(this, _WebSocket))(`ws://${__privateGet(this, _config).host}:${__privateGet(this, _config).port}/api/v1/ws`);
    __privateSet(this, _socket, socket);
    socket.addEventListener("open", () => {
      if (__privateGet(this, _pollTimer)) {
        globalThis.clearInterval(__privateGet(this, _pollTimer));
        __privateSet(this, _pollTimer, 0);
      }
      globalThis.clearTimeout(__privateGet(this, _webSocketRetryTimer));
      this.emit("connection", { state: "connected", message: "" });
    });
    socket.addEventListener("message", (event) => __privateMethod(this, _PearYoutubeMusicSource_instances, handleSocketMessage_fn).call(this, event.data));
    socket.addEventListener("error", () => __privateMethod(this, _PearYoutubeMusicSource_instances, fallbackFromWebSocket_fn).call(this));
    socket.addEventListener("close", () => {
      if (__privateGet(this, _stopped)) {
        return;
      }
      if (__privateGet(this, _config).transport === "ws") {
        this.emit("connection", { state: "disconnected", message: "Pear WebSocket disconnected" });
        __privateSet(this, _reconnectTimer, globalThis.setTimeout(() => __privateMethod(this, _PearYoutubeMusicSource_instances, connectWebSocket_fn).call(this), 3e3));
      } else {
        __privateMethod(this, _PearYoutubeMusicSource_instances, fallbackFromWebSocket_fn).call(this);
      }
    });
  };
  fallbackFromWebSocket_fn = function() {
    if (__privateGet(this, _config).transport === "ws") {
      return;
    }
    if (!__privateGet(this, _pollTimer)) {
      this.emit("connection", { state: "connecting", message: "Using polling fallback" });
      __privateMethod(this, _PearYoutubeMusicSource_instances, startPolling_fn).call(this);
    }
    __privateMethod(this, _PearYoutubeMusicSource_instances, scheduleWebSocketRetry_fn).call(this);
  };
  startPolling_fn = function() {
    __privateMethod(this, _PearYoutubeMusicSource_instances, pollOnce_fn).call(this);
    __privateSet(this, _pollTimer, globalThis.setInterval(() => __privateMethod(this, _PearYoutubeMusicSource_instances, pollOnce_fn).call(this), 3e3));
  };
  pollOnce_fn = async function() {
    try {
      const response = await __privateMethod(this, _PearYoutubeMusicSource_instances, requestSong_fn).call(this);
      if (response.status === 204) {
        this.emit("connection", { state: "waiting", message: "Pear is reachable. No song is playing." });
        return;
      }
      if (!response.ok) {
        throw new Error(`Pear returned ${response.status}`);
      }
      __privateMethod(this, _PearYoutubeMusicSource_instances, publishPearPayload_fn).call(this, await response.json());
      this.emit("connection", { state: "connected", message: "Polling Pear Desktop" });
    } catch (error) {
      this.emit("connection", { state: "disconnected", message: error.message });
    }
  };
  requestSong_fn = function() {
    if (!__privateGet(this, _fetch)) {
      throw new Error("Fetch is not available in this browser.");
    }
    return __privateGet(this, _fetch).call(this, `http://${__privateGet(this, _config).host}:${__privateGet(this, _config).port}/api/v1/song`);
  };
  handleSocketMessage_fn = function(rawMessage) {
    var _a, _b, _c, _d, _e, _f;
    try {
      const message = JSON.parse(rawMessage);
      const eventType = (_b = (_a = message.type) != null ? _a : message.event) != null ? _b : message.eventType;
      if (!["PLAYER_INFO", "VIDEO_CHANGED", "PLAYER_STATE_CHANGED", "POSITION_CHANGED"].includes(eventType)) {
        return;
      }
      const song = (_f = (_e = (_c = message.payload) == null ? void 0 : _c.song) != null ? _e : (_d = message.data) == null ? void 0 : _d.song) != null ? _f : message.song;
      if (song) {
        const payload = {
          ...song,
          elapsedSeconds: readPosition(message, song.elapsedSeconds),
          isPaused: typeof message.isPlaying === "boolean" ? !message.isPlaying : song.isPaused
        };
        __privateMethod(this, _PearYoutubeMusicSource_instances, publishPearPayload_fn).call(this, __privateMethod(this, _PearYoutubeMusicSource_instances, mergeSameTrackMissingFields_fn).call(this, payload));
        return;
      }
      __privateMethod(this, _PearYoutubeMusicSource_instances, publishPartialState_fn).call(this, message);
    } catch (e) {
      this.emit("connection", { state: "disconnected", message: "Pear sent an unreadable message" });
    }
  };
  publishPearPayload_fn = function(payload) {
    __privateSet(this, _state2, normalizePearSong(payload));
    this.emit("state", __privateGet(this, _state2));
  };
  publishPartialState_fn = function(message) {
    if (!__privateGet(this, _state2)) {
      return;
    }
    __privateSet(this, _state2, normalizePlayerState({
      ...__privateGet(this, _state2),
      elapsedSeconds: readPosition(message, __privateGet(this, _state2).elapsedSeconds),
      isPlaying: typeof message.isPlaying === "boolean" ? message.isPlaying : __privateGet(this, _state2).isPlaying,
      updatedAt: Date.now()
    }));
    this.emit("state", __privateGet(this, _state2));
  };
  mergeSameTrackMissingFields_fn = function(payload) {
    var _a, _b;
    if (!__privateGet(this, _state2) || !isSameTrack(__privateGet(this, _state2), payload)) {
      return payload;
    }
    return {
      ...payload,
      album: (_a = payload.album) != null ? _a : __privateGet(this, _state2).album,
      imageSrc: (_b = payload.imageSrc) != null ? _b : __privateGet(this, _state2).artworkUrl
    };
  };
  scheduleWebSocketRetry_fn = function() {
    if (__privateGet(this, _config).transport !== "auto" || __privateGet(this, _webSocketRetryTimer)) {
      return;
    }
    __privateSet(this, _webSocketRetryTimer, globalThis.setTimeout(() => {
      __privateSet(this, _webSocketRetryTimer, 0);
      if (!__privateGet(this, _stopped)) {
        __privateMethod(this, _PearYoutubeMusicSource_instances, connectWebSocket_fn).call(this);
      }
    }, 3e3));
  };
  function readPosition(message, fallback) {
    var _a, _b, _c, _d;
    const value = Number((_d = (_b = message.position) != null ? _b : (_a = message.payload) == null ? void 0 : _a.position) != null ? _d : (_c = message.data) == null ? void 0 : _c.position);
    return Number.isFinite(value) ? value : fallback;
  }
  function isSameTrack(state, payload) {
    const payloadTrackId = payload.videoId || payload.url || payload.title;
    if (state.trackId && payloadTrackId) {
      return state.trackId === payloadTrackId;
    }
    return state.title === payload.title && state.artist === payload.artist;
  }

  // src/sources/sourceRegistry.js
  function createMusicSource(config, dependencies) {
    if (config.integration === "mock") {
      return new MockMusicSource();
    }
    if (config.integration === "pear-youtube-music") {
      return new PearYoutubeMusicSource(config, dependencies);
    }
    throw new Error(`Unsupported integration: ${config.integration}`);
  }

  // src/state/progressClock.js
  function getDisplayedProgress(state, now = Date.now()) {
    const durationSeconds = Math.max(0, Number(state == null ? void 0 : state.durationSeconds) || 0);
    const baseElapsed = Math.max(0, Number(state == null ? void 0 : state.elapsedSeconds) || 0);
    const updatedAt = Number(state == null ? void 0 : state.updatedAt) || now;
    const deltaSeconds = (state == null ? void 0 : state.isPlaying) ? Math.max(0, now - updatedAt) / 1e3 : 0;
    const elapsedSeconds = durationSeconds ? Math.min(durationSeconds, baseElapsed + deltaSeconds) : baseElapsed + deltaSeconds;
    const percent = durationSeconds ? elapsedSeconds / durationSeconds * 100 : 0;
    return {
      elapsedSeconds,
      durationSeconds,
      percent: Math.min(100, Math.max(0, percent))
    };
  }
  function formatTime(totalSeconds) {
    const safeSeconds = Math.max(0, Math.floor(Number(totalSeconds) || 0));
    const minutes = Math.floor(safeSeconds / 60);
    const seconds = String(safeSeconds % 60).padStart(2, "0");
    return `${minutes}:${seconds}`;
  }

  // src/ui/overlayView.js
  var _root, _artEl, _titleEl, _detailsEl, _progressEl, _timeEl;
  var OverlayView = class {
    constructor(root) {
      __privateAdd(this, _root);
      __privateAdd(this, _artEl);
      __privateAdd(this, _titleEl);
      __privateAdd(this, _detailsEl);
      __privateAdd(this, _progressEl);
      __privateAdd(this, _timeEl);
      __privateSet(this, _root, root);
      __privateGet(this, _root).innerHTML = `
      <section class="sj-widget" aria-live="polite">
        <div class="sj-art" aria-hidden="true"><span>SJ</span></div>
        <div class="sj-copy">
          <h1 class="sj-title"><span>Connecting...</span></h1>
          <p class="sj-details"><span></span></p>
          <div class="sj-progress-row">
            <div class="sj-progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
              <span class="sj-progress-fill"></span>
            </div>
            <span class="sj-time">0:00</span>
          </div>
        </div>
      </section>
    `;
      __privateSet(this, _artEl, __privateGet(this, _root).querySelector(".sj-art"));
      __privateSet(this, _titleEl, __privateGet(this, _root).querySelector(".sj-title"));
      __privateSet(this, _detailsEl, __privateGet(this, _root).querySelector(".sj-details"));
      __privateSet(this, _progressEl, __privateGet(this, _root).querySelector(".sj-progress"));
      __privateSet(this, _timeEl, __privateGet(this, _root).querySelector(".sj-time"));
    }
    setTheme(theme) {
      document.documentElement.dataset.theme = theme;
    }
    setView(view) {
      __privateGet(this, _root).dataset.view = view;
    }
    renderConfigurationError(errors) {
      __privateGet(this, _root).innerHTML = `
      <section class="sj-widget sj-error" aria-live="assertive">
        <div class="sj-copy">
          <h1 class="sj-title">Widget setup needed</h1>
          <p class="sj-error-message">${escapeHtml(errors.join(" "))}</p>
          <a class="sj-link" href="setup.html">Open setup</a>
        </div>
      </section>
    `;
    }
    renderConnection(connection) {
      __privateGet(this, _root).dataset.connection = connection.state;
      if (connection.state === "waiting") {
        setScrollingText(__privateGet(this, _titleEl), "Waiting for music");
        setScrollingText(__privateGet(this, _detailsEl), "Start a track in YouTube Music");
      }
    }
    renderTrack(state, now = Date.now()) {
      const progress = getDisplayedProgress(state, now);
      setScrollingText(__privateGet(this, _titleEl), state.title);
      setScrollingText(__privateGet(this, _detailsEl), formatTrackDetails(state));
      __privateGet(this, _progressEl).setAttribute("aria-valuenow", String(Math.round(progress.percent)));
      __privateGet(this, _progressEl).querySelector(".sj-progress-fill").style.inlineSize = `${progress.percent}%`;
      __privateGet(this, _timeEl).textContent = formatTime(progress.elapsedSeconds);
      if (state.artworkUrl) {
        __privateGet(this, _artEl).style.backgroundImage = `url("${state.artworkUrl.replaceAll('"', "%22")}")`;
        __privateGet(this, _artEl).classList.add("has-art");
      } else {
        __privateGet(this, _artEl).style.backgroundImage = "";
        __privateGet(this, _artEl).classList.remove("has-art");
      }
    }
  };
  _root = new WeakMap();
  _artEl = new WeakMap();
  _titleEl = new WeakMap();
  _detailsEl = new WeakMap();
  _progressEl = new WeakMap();
  _timeEl = new WeakMap();
  function formatTrackDetails(state) {
    return [state.artist, state.album].filter(Boolean).join(" - ");
  }
  function setScrollingText(element, value) {
    const text = value || "";
    let content = element.querySelector("span");
    if (!content) {
      content = document.createElement("span");
      element.textContent = "";
      element.append(content);
    }
    if (content.textContent !== text) {
      content.textContent = text;
      element.classList.remove("is-overflowing");
    }
    requestAnimationFrame(() => {
      const isOverflowing = content.scrollWidth > element.clientWidth;
      element.classList.toggle("is-overflowing", isOverflowing);
      if (isOverflowing) {
        const distance = content.scrollWidth - element.clientWidth;
        element.style.setProperty("--sj-scroll-distance", `${distance + 18}px`);
        element.style.setProperty("--sj-scroll-duration", `${Math.max(10, Math.min(28, distance / 12))}s`);
      } else {
        element.style.removeProperty("--sj-scroll-distance");
        element.style.removeProperty("--sj-scroll-duration");
      }
    });
  }
  function escapeHtml(value) {
    return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
  }

  // src/app/overlayApp.js
  function startOverlayApp(root = document.querySelector("#app"), href = globalThis.location.href) {
    const config = parseOverlayConfig(href);
    const view = new OverlayView(root);
    if (!config.ok) {
      view.renderConfigurationError(config.errors);
      return { config, stop() {
      } };
    }
    view.setTheme(config.theme);
    view.setView(config.initialView);
    loadCustomCss(config.customCss);
    const source = createMusicSource(config);
    let currentView = config.initialView;
    let idleTimer = 0;
    let progressTimer = 0;
    let latestState = null;
    const restoreInitialView = () => {
      currentView = config.initialView;
      view.setView(currentView);
      scheduleIdle();
    };
    const scheduleIdle = () => {
      globalThis.clearTimeout(idleTimer);
      if (config.idleMode === "none") {
        return;
      }
      idleTimer = globalThis.setTimeout(() => {
        currentView = config.idleMode === "hide" ? "hidden" : "compact";
        view.setView(currentView);
      }, config.idleAfter * 1e3);
    };
    source.on("connection", (connection) => {
      view.renderConnection(connection);
      if (["connected", "waiting"].includes(connection.state)) {
        restoreInitialView();
      }
    });
    source.on("state", (state) => {
      const previousTrackId = latestState == null ? void 0 : latestState.trackId;
      latestState = state;
      view.renderTrack(state);
      if (state.trackId && state.trackId !== previousTrackId) {
        restoreInitialView();
      }
    });
    source.connect();
    progressTimer = globalThis.setInterval(() => {
      if (latestState && currentView !== "hidden") {
        view.renderTrack(latestState);
      }
    }, 1e3);
    scheduleIdle();
    return {
      config,
      stop() {
        globalThis.clearTimeout(idleTimer);
        globalThis.clearInterval(progressTimer);
        source.disconnect();
      }
    };
  }
  function loadCustomCss(path) {
    if (!path) {
      return;
    }
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = path;
    document.head.append(link);
  }
  if (typeof document !== "undefined") {
    startOverlayApp();
  }
  return __toCommonJS(overlayApp_exports);
})();
