/*
 * Generated from src/ by scripts/build-browser-bundles.js.
 * Do not edit this file directly; update src/ and run npm run build.
 */
var StreamJamsSetup = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __typeError = (msg) => {
    throw TypeError(msg);
  };
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
  var __accessCheck = (obj, member, msg) => member.has(obj) || __typeError("Cannot " + msg);
  var __privateGet = (obj, member, getter) => (__accessCheck(obj, member, "read from private field"), getter ? getter.call(obj) : member.get(obj));
  var __privateAdd = (obj, member, value) => member.has(obj) ? __typeError("Cannot add the same private member more than once") : member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
  var __privateSet = (obj, member, value, setter) => (__accessCheck(obj, member, "write to private field"), setter ? setter.call(obj, value) : member.set(obj, value), value);
  var __privateMethod = (obj, member, method) => (__accessCheck(obj, member, "access private method"), method);

  // src/app/setupApp.js
  var setupApp_exports = {};
  __export(setupApp_exports, {
    startSetupApp: () => startSetupApp
  });

  // src/config/setupConfig.js
  var SETUP_STORAGE_KEY = "stream-jams.setup";
  var setupIntegrations = [
    {
      id: "pear-youtube-music",
      name: "Pear Desktop",
      description: "Use Pear Desktop's API Server plugin to read YouTube Music playback from this machine.",
      status: "available"
    },
    {
      id: "spotify",
      name: "Spotify",
      description: "Spotify setup is planned for a future release.",
      status: "coming-soon"
    }
  ];
  var setupDefaults = {
    integration: "pear-youtube-music",
    host: "127.0.0.1",
    port: 26538,
    transport: "auto",
    initialView: "full",
    idleMode: "none",
    idleAfter: 30,
    theme: "dark",
    customCss: ""
  };
  var SAFE_KEYS = Object.keys(setupDefaults);
  function loadSetupPreferences(storage = globalThis.localStorage) {
    if (!storage) {
      return { ...setupDefaults };
    }
    try {
      const saved = JSON.parse(storage.getItem(SETUP_STORAGE_KEY) || "{}");
      return sanitizeSetupPreferences(saved);
    } catch (e) {
      return { ...setupDefaults };
    }
  }
  function saveSetupPreferences(values, storage = globalThis.localStorage) {
    if (!storage) {
      return;
    }
    storage.setItem(SETUP_STORAGE_KEY, JSON.stringify(sanitizeSetupPreferences(values)));
  }
  function sanitizeSetupPreferences(values) {
    const next = { ...setupDefaults };
    for (const key of SAFE_KEYS) {
      if (Object.hasOwn(values != null ? values : {}, key)) {
        next[key] = values[key];
      }
    }
    next.port = clampInteger(next.port, setupDefaults.port, 1, 65535);
    next.idleAfter = clampInteger(next.idleAfter, setupDefaults.idleAfter, 1, 600);
    return next;
  }
  function buildOverlayUrl(values, baseHref = ((_b) => (_b = ((_a) => (_a = globalThis.location) == null ? void 0 : _a.href)()) != null ? _b : "")()) {
    const base = new URL("index.html", baseHref);
    const settings = sanitizeSetupPreferences(values);
    for (const [key, value] of Object.entries(settings)) {
      if (value !== "" && value !== void 0 && value !== null) {
        base.searchParams.set(key, String(value));
      }
    }
    return base.href;
  }
  function clampInteger(value, fallback, min, max) {
    const number = Number(value);
    if (!Number.isInteger(number)) {
      return fallback;
    }
    return Math.min(max, Math.max(min, number));
  }

  // src/sources/musicSource.js
  var _listeners;
  var EventEmitter = class {
    constructor() {
      __privateAdd(this, _listeners, /* @__PURE__ */ new Map());
    }
    on(type, handler) {
      var _a;
      const handlers = (_a = __privateGet(this, _listeners).get(type)) != null ? _a : /* @__PURE__ */ new Set();
      handlers.add(handler);
      __privateGet(this, _listeners).set(type, handlers);
      return () => handlers.delete(handler);
    }
    emit(type, payload) {
      var _a;
      for (const handler of (_a = __privateGet(this, _listeners).get(type)) != null ? _a : []) {
        handler(payload);
      }
    }
  };
  _listeners = new WeakMap();

  // src/state/playerState.js
  function normalizePearSong(payload, now = Date.now()) {
    return normalizePlayerState({
      trackId: payload.videoId || payload.url || payload.title,
      title: payload.title,
      artist: payload.artist,
      album: payload.album,
      artworkUrl: payload.imageSrc,
      durationSeconds: payload.songDuration,
      elapsedSeconds: payload.elapsedSeconds,
      isPlaying: payload.isPaused === false,
      sourceName: "YouTube Music",
      updatedAt: now
    });
  }
  function normalizePlayerState(input = {}) {
    const durationSeconds = positiveNumber(input.durationSeconds);
    const elapsedSeconds = clamp(positiveNumber(input.elapsedSeconds), 0, durationSeconds || 0);
    return {
      trackId: stringOrFallback(input.trackId, ""),
      title: stringOrFallback(input.title, "No track"),
      artist: stringOrFallback(input.artist, "Unknown artist"),
      album: stringOrFallback(input.album, ""),
      artworkUrl: stringOrFallback(input.artworkUrl, ""),
      durationSeconds,
      elapsedSeconds,
      isPlaying: Boolean(input.isPlaying),
      sourceName: stringOrFallback(input.sourceName, ""),
      updatedAt: Number.isFinite(input.updatedAt) ? input.updatedAt : Date.now()
    };
  }
  function stringOrFallback(value, fallback) {
    return typeof value === "string" && value.trim() ? value.trim() : fallback;
  }
  function positiveNumber(value) {
    const number = Number(value);
    return Number.isFinite(number) && number > 0 ? number : 0;
  }
  function clamp(value, min, max) {
    if (max <= min) {
      return min;
    }
    return Math.min(max, Math.max(min, value));
  }

  // src/sources/pearYoutubeMusicSource.js
  var _config, _fetch, _WebSocket, _socket, _pollTimer, _reconnectTimer, _webSocketRetryTimer, _state, _stopped, _PearYoutubeMusicSource_instances, connectWebSocket_fn, fallbackFromWebSocket_fn, startPolling_fn, pollOnce_fn, requestSong_fn, handleSocketMessage_fn, publishPearPayload_fn, publishPartialState_fn, mergeSameTrackMissingFields_fn, scheduleWebSocketRetry_fn;
  var PearYoutubeMusicSource = class extends EventEmitter {
    constructor(config, dependencies = {}) {
      var _a, _b, _c;
      super();
      __privateAdd(this, _PearYoutubeMusicSource_instances);
      __privateAdd(this, _config);
      __privateAdd(this, _fetch);
      __privateAdd(this, _WebSocket);
      __privateAdd(this, _socket, null);
      __privateAdd(this, _pollTimer, 0);
      __privateAdd(this, _reconnectTimer, 0);
      __privateAdd(this, _webSocketRetryTimer, 0);
      __privateAdd(this, _state, null);
      __privateAdd(this, _stopped, false);
      __privateSet(this, _config, config);
      __privateSet(this, _fetch, (_b = dependencies.fetch) != null ? _b : (_a = globalThis.fetch) == null ? void 0 : _a.bind(globalThis));
      __privateSet(this, _WebSocket, (_c = dependencies.WebSocket) != null ? _c : globalThis.WebSocket);
    }
    connect() {
      __privateSet(this, _stopped, false);
      this.emit("connection", { state: "connecting", message: "Connecting to Pear Desktop" });
      if (__privateGet(this, _config).transport === "poll") {
        __privateMethod(this, _PearYoutubeMusicSource_instances, startPolling_fn).call(this);
        return;
      }
      __privateMethod(this, _PearYoutubeMusicSource_instances, connectWebSocket_fn).call(this);
    }
    disconnect() {
      var _a, _b;
      __privateSet(this, _stopped, true);
      globalThis.clearInterval(__privateGet(this, _pollTimer));
      globalThis.clearTimeout(__privateGet(this, _reconnectTimer));
      globalThis.clearTimeout(__privateGet(this, _webSocketRetryTimer));
      (_b = (_a = __privateGet(this, _socket)) == null ? void 0 : _a.close) == null ? void 0 : _b.call(_a);
      this.emit("connection", { state: "disconnected", message: "Disconnected" });
    }
    getCurrentState() {
      return __privateGet(this, _state);
    }
    async testConnection() {
      const response = await __privateMethod(this, _PearYoutubeMusicSource_instances, requestSong_fn).call(this);
      return response.ok || response.status === 204;
    }
  };
  _config = new WeakMap();
  _fetch = new WeakMap();
  _WebSocket = new WeakMap();
  _socket = new WeakMap();
  _pollTimer = new WeakMap();
  _reconnectTimer = new WeakMap();
  _webSocketRetryTimer = new WeakMap();
  _state = new WeakMap();
  _stopped = new WeakMap();
  _PearYoutubeMusicSource_instances = new WeakSet();
  connectWebSocket_fn = function() {
    if (!__privateGet(this, _WebSocket)) {
      __privateMethod(this, _PearYoutubeMusicSource_instances, fallbackFromWebSocket_fn).call(this);
      return;
    }
    const socket = new (__privateGet(this, _WebSocket))(`ws://${__privateGet(this, _config).host}:${__privateGet(this, _config).port}/api/v1/ws`);
    __privateSet(this, _socket, socket);
    socket.addEventListener("open", () => {
      if (__privateGet(this, _pollTimer)) {
        globalThis.clearInterval(__privateGet(this, _pollTimer));
        __privateSet(this, _pollTimer, 0);
      }
      globalThis.clearTimeout(__privateGet(this, _webSocketRetryTimer));
      this.emit("connection", { state: "connected", message: "" });
    });
    socket.addEventListener("message", (event) => __privateMethod(this, _PearYoutubeMusicSource_instances, handleSocketMessage_fn).call(this, event.data));
    socket.addEventListener("error", () => __privateMethod(this, _PearYoutubeMusicSource_instances, fallbackFromWebSocket_fn).call(this));
    socket.addEventListener("close", () => {
      if (__privateGet(this, _stopped)) {
        return;
      }
      if (__privateGet(this, _config).transport === "ws") {
        this.emit("connection", { state: "disconnected", message: "Pear WebSocket disconnected" });
        __privateSet(this, _reconnectTimer, globalThis.setTimeout(() => __privateMethod(this, _PearYoutubeMusicSource_instances, connectWebSocket_fn).call(this), 3e3));
      } else {
        __privateMethod(this, _PearYoutubeMusicSource_instances, fallbackFromWebSocket_fn).call(this);
      }
    });
  };
  fallbackFromWebSocket_fn = function() {
    if (__privateGet(this, _config).transport === "ws") {
      return;
    }
    if (!__privateGet(this, _pollTimer)) {
      this.emit("connection", { state: "connecting", message: "Using polling fallback" });
      __privateMethod(this, _PearYoutubeMusicSource_instances, startPolling_fn).call(this);
    }
    __privateMethod(this, _PearYoutubeMusicSource_instances, scheduleWebSocketRetry_fn).call(this);
  };
  startPolling_fn = function() {
    __privateMethod(this, _PearYoutubeMusicSource_instances, pollOnce_fn).call(this);
    __privateSet(this, _pollTimer, globalThis.setInterval(() => __privateMethod(this, _PearYoutubeMusicSource_instances, pollOnce_fn).call(this), 3e3));
  };
  pollOnce_fn = async function() {
    try {
      const response = await __privateMethod(this, _PearYoutubeMusicSource_instances, requestSong_fn).call(this);
      if (response.status === 204) {
        this.emit("connection", { state: "waiting", message: "Pear is reachable. No song is playing." });
        return;
      }
      if (!response.ok) {
        throw new Error(`Pear returned ${response.status}`);
      }
      __privateMethod(this, _PearYoutubeMusicSource_instances, publishPearPayload_fn).call(this, await response.json());
      this.emit("connection", { state: "connected", message: "Polling Pear Desktop" });
    } catch (error) {
      this.emit("connection", { state: "disconnected", message: error.message });
    }
  };
  requestSong_fn = function() {
    if (!__privateGet(this, _fetch)) {
      throw new Error("Fetch is not available in this browser.");
    }
    return __privateGet(this, _fetch).call(this, `http://${__privateGet(this, _config).host}:${__privateGet(this, _config).port}/api/v1/song`);
  };
  handleSocketMessage_fn = function(rawMessage) {
    var _a, _b, _c, _d, _e, _f;
    try {
      const message = JSON.parse(rawMessage);
      const eventType = (_b = (_a = message.type) != null ? _a : message.event) != null ? _b : message.eventType;
      if (!["PLAYER_INFO", "VIDEO_CHANGED", "PLAYER_STATE_CHANGED", "POSITION_CHANGED"].includes(eventType)) {
        return;
      }
      const song = (_f = (_e = (_c = message.payload) == null ? void 0 : _c.song) != null ? _e : (_d = message.data) == null ? void 0 : _d.song) != null ? _f : message.song;
      if (song) {
        const payload = {
          ...song,
          elapsedSeconds: readPosition(message, song.elapsedSeconds),
          isPaused: typeof message.isPlaying === "boolean" ? !message.isPlaying : song.isPaused
        };
        __privateMethod(this, _PearYoutubeMusicSource_instances, publishPearPayload_fn).call(this, __privateMethod(this, _PearYoutubeMusicSource_instances, mergeSameTrackMissingFields_fn).call(this, payload));
        return;
      }
      __privateMethod(this, _PearYoutubeMusicSource_instances, publishPartialState_fn).call(this, message);
    } catch (e) {
      this.emit("connection", { state: "disconnected", message: "Pear sent an unreadable message" });
    }
  };
  publishPearPayload_fn = function(payload) {
    __privateSet(this, _state, normalizePearSong(payload));
    this.emit("state", __privateGet(this, _state));
  };
  publishPartialState_fn = function(message) {
    if (!__privateGet(this, _state)) {
      return;
    }
    __privateSet(this, _state, normalizePlayerState({
      ...__privateGet(this, _state),
      elapsedSeconds: readPosition(message, __privateGet(this, _state).elapsedSeconds),
      isPlaying: typeof message.isPlaying === "boolean" ? message.isPlaying : __privateGet(this, _state).isPlaying,
      updatedAt: Date.now()
    }));
    this.emit("state", __privateGet(this, _state));
  };
  mergeSameTrackMissingFields_fn = function(payload) {
    var _a, _b;
    if (!__privateGet(this, _state) || !isSameTrack(__privateGet(this, _state), payload)) {
      return payload;
    }
    return {
      ...payload,
      album: (_a = payload.album) != null ? _a : __privateGet(this, _state).album,
      imageSrc: (_b = payload.imageSrc) != null ? _b : __privateGet(this, _state).artworkUrl
    };
  };
  scheduleWebSocketRetry_fn = function() {
    if (__privateGet(this, _config).transport !== "auto" || __privateGet(this, _webSocketRetryTimer)) {
      return;
    }
    __privateSet(this, _webSocketRetryTimer, globalThis.setTimeout(() => {
      __privateSet(this, _webSocketRetryTimer, 0);
      if (!__privateGet(this, _stopped)) {
        __privateMethod(this, _PearYoutubeMusicSource_instances, connectWebSocket_fn).call(this);
      }
    }, 3e3));
  };
  function readPosition(message, fallback) {
    var _a, _b, _c, _d;
    const value = Number((_d = (_b = message.position) != null ? _b : (_a = message.payload) == null ? void 0 : _a.position) != null ? _d : (_c = message.data) == null ? void 0 : _c.position);
    return Number.isFinite(value) ? value : fallback;
  }
  function isSameTrack(state, payload) {
    const payloadTrackId = payload.videoId || payload.url || payload.title;
    if (state.trackId && payloadTrackId) {
      return state.trackId === payloadTrackId;
    }
    return state.title === payload.title && state.artist === payload.artist;
  }

  // src/ui/setupView.js
  var _form, _urlOutput, _status, _sourceMenu, _pearPanel, _spotifyPanel, _onChange, _onTest;
  var SetupView = class {
    constructor(root, initialValues, handlers) {
      __privateAdd(this, _form);
      __privateAdd(this, _urlOutput);
      __privateAdd(this, _status);
      __privateAdd(this, _sourceMenu);
      __privateAdd(this, _pearPanel);
      __privateAdd(this, _spotifyPanel);
      __privateAdd(this, _onChange);
      __privateAdd(this, _onTest);
      __privateSet(this, _onChange, handlers.onChange);
      __privateSet(this, _onTest, handlers.onTest);
      root.innerHTML = `
      <main class="setup-shell">
        <section class="setup-intro">
          <p class="setup-label">Stream Jams Music Widget</p>
          <h1>Choose a music source</h1>
          <p>Select the playback source Stream Jams should read from. Each source can have its own setup requirements.</p>
        </section>
        <section class="setup-source-menu">
          ${setupIntegrations.map(sourceCard).join("")}
        </section>
        <section class="setup-panel" data-panel="pear" hidden>
          <div class="setup-panel-heading">
            <button class="setup-back" type="button" data-action="back">Back</button>
            <div>
              <p class="setup-label">Pear Desktop</p>
              <h2>Build an OBS overlay URL</h2>
              <p>Connect Pear Desktop's YouTube Music API Server plugin, choose the overlay behavior, then use the generated URL as an OBS browser source.</p>
            </div>
          </div>
          <form class="setup-form">
            <input type="hidden" name="integration" value="pear-youtube-music">
            <fieldset>
              <legend>Pear Desktop</legend>
              <ol class="setup-steps">
                <li>Open Pear Desktop.</li>
                <li>Enable the API Server plugin.</li>
                <li>Set API Server auth strategy to NONE.</li>
                <li>Confirm the host and port below.</li>
              </ol>
              <div class="setup-grid">
                <label>Host <input name="host" value="${initialValues.host}" autocomplete="off"></label>
                <label>Port <input name="port" type="number" min="1" max="65535" value="${initialValues.port}"></label>
                <label>Transport
                  <select name="transport">
                    ${option("auto", "Auto", initialValues.transport)}
                    ${option("ws", "WebSocket only", initialValues.transport)}
                    ${option("poll", "Polling only", initialValues.transport)}
                  </select>
                </label>
              </div>
            </fieldset>
            <fieldset>
              <legend>Overlay</legend>
              <div class="setup-grid">
                <label>Theme
                  <select name="theme">
                    ${option("dark", "Dark", initialValues.theme)}
                    ${option("light", "Light", initialValues.theme)}
                  </select>
                </label>
                <label>Initial view
                  <select name="initialView">
                    ${option("full", "Full", initialValues.initialView)}
                    ${option("compact", "Compact", initialValues.initialView)}
                  </select>
                </label>
                <label>Idle mode
                  <select name="idleMode">
                    ${option("none", "None", initialValues.idleMode)}
                    ${option("hide", "Hide", initialValues.idleMode)}
                    ${option("compact", "Compact", initialValues.idleMode)}
                  </select>
                </label>
                <label>Idle after
                  <input name="idleAfter" type="number" min="1" max="600" value="${initialValues.idleAfter}">
                </label>
                <label class="setup-wide">Custom CSS
                  <input name="customCss" value="${initialValues.customCss}" placeholder="custom-theme.css">
                </label>
              </div>
            </fieldset>
            <div class="setup-actions">
              <button type="button" data-action="test">Test connection</button>
              <a class="setup-preview" href="#" target="_blank" rel="noreferrer">Preview overlay</a>
            </div>
          </form>
          <section class="setup-output">
            <label>OBS URL <output></output></label>
            <p class="setup-status" role="status"></p>
          </section>
        </section>
        <section class="setup-panel setup-placeholder" data-panel="spotify" hidden>
          <button class="setup-back" type="button" data-action="back">Back</button>
          <p class="setup-label">Spotify</p>
          <h2>Spotify support is coming soon</h2>
          <p>Spotify integration will be added in a future release. For now, use Pear Desktop for YouTube Music playback.</p>
        </section>
      </main>
    `;
      __privateSet(this, _form, root.querySelector("form"));
      __privateSet(this, _urlOutput, root.querySelector("output"));
      __privateSet(this, _status, root.querySelector(".setup-status"));
      __privateSet(this, _sourceMenu, root.querySelector(".setup-source-menu"));
      __privateSet(this, _pearPanel, root.querySelector('[data-panel="pear"]'));
      __privateSet(this, _spotifyPanel, root.querySelector('[data-panel="spotify"]'));
      root.querySelectorAll("[data-source]").forEach((button) => {
        button.addEventListener("click", () => this.showSource(button.dataset.source));
      });
      root.querySelectorAll('[data-action="back"]').forEach((button) => {
        button.addEventListener("click", () => this.showSourceMenu());
      });
      root.querySelector("[data-action='test']").addEventListener("click", () => __privateGet(this, _onTest).call(this, this.readValues()));
      __privateGet(this, _form).addEventListener("input", () => __privateGet(this, _onChange).call(this, this.readValues()));
    }
    readValues() {
      return Object.fromEntries(new FormData(__privateGet(this, _form)).entries());
    }
    renderUrl(values) {
      const url = buildOverlayUrl(values, globalThis.location.href);
      __privateGet(this, _urlOutput).textContent = url;
      __privateGet(this, _urlOutput).title = url;
      __privateGet(this, _form).querySelector(".setup-preview").href = url;
    }
    renderStatus(message, tone = "neutral") {
      __privateGet(this, _status).textContent = message;
      __privateGet(this, _status).dataset.tone = tone;
    }
    showSource(sourceId) {
      __privateGet(this, _sourceMenu).hidden = true;
      __privateGet(this, _pearPanel).hidden = sourceId !== "pear-youtube-music";
      __privateGet(this, _spotifyPanel).hidden = sourceId !== "spotify";
      if (sourceId === "pear-youtube-music") {
        this.renderUrl(this.readValues());
      }
    }
    showSourceMenu() {
      __privateGet(this, _sourceMenu).hidden = false;
      __privateGet(this, _pearPanel).hidden = true;
      __privateGet(this, _spotifyPanel).hidden = true;
    }
  };
  _form = new WeakMap();
  _urlOutput = new WeakMap();
  _status = new WeakMap();
  _sourceMenu = new WeakMap();
  _pearPanel = new WeakMap();
  _spotifyPanel = new WeakMap();
  _onChange = new WeakMap();
  _onTest = new WeakMap();
  function sourceCard(integration) {
    const statusText = integration.status === "coming-soon" ? "Coming soon" : "Available";
    return `
    <button class="setup-source-card" type="button" data-source="${integration.id}">
      <span>${integration.name}</span>
      <small>${integration.description}</small>
      <strong>${statusText}</strong>
    </button>
  `;
  }
  function option(value, label, selected) {
    const selectedAttr = value === selected ? " selected" : "";
    return `<option value="${value}"${selectedAttr}>${label}</option>`;
  }

  // src/app/setupApp.js
  function startSetupApp(root = document.querySelector("#app")) {
    const preferences = loadSetupPreferences();
    const view = new SetupView(root, preferences, {
      onChange(values) {
        saveSetupPreferences(values);
        view.renderUrl(values);
      },
      async onTest(values) {
        view.renderStatus("Testing Pear Desktop...", "neutral");
        try {
          const source = new PearYoutubeMusicSource({
            integration: "pear-youtube-music",
            host: values.host,
            port: Number(values.port),
            transport: "poll"
          });
          const ok = await source.testConnection();
          view.renderStatus(
            ok ? "Pear Desktop responded. This URL is ready for OBS." : "Pear Desktop did not return a usable response.",
            ok ? "success" : "error"
          );
        } catch (error) {
          view.renderStatus(error.message, "error");
        }
      }
    });
    view.renderUrl(preferences);
    return view;
  }
  if (typeof document !== "undefined") {
    startSetupApp();
  }
  return __toCommonJS(setupApp_exports);
})();
